name: Build and Push React App Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "web development"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/upt-faing-epis/proyecto-si8811a-2024-ii-u1-web-development/juegosflorales:latest
          build-args: |
            VITE_SERVER_EVENTO=${{ secrets.VITE_SERVER_EVENTO }}
            VITE_SERVER_EQUIPO=${{ secrets.VITE_SERVER_EQUIPO }}
            VITE_SERVER_PARTICIPANTE=${{ secrets.VITE_SERVER_PARTICIPANTE }}
            VITE_SERVER_LUGARES=${{ secrets.VITE_SERVER_LUGARES }}
            VITE_SERVER_CATEGORIAS=${{ secrets.VITE_SERVER_CATEGORIAS }}
